require 'dmtest/tests/clone/creation_tests'
require 'dmtest/tests/clone/fs_benchmark'
require 'dmtest/tests/clone/throughput_tests'
require 'dmtest/tests/clone/commit_tests'
require 'dmtest/tests/clone/consistency_tests'
